export default facts = [
  "Your eyes focus on 50 different objects every second",
  "The only organ more complex than the eye is the brain.",
  "Your eyes can distinguish approximately 10 million different colors.",
  "It is impossible to sneeze with your eyes open.",
  "Ommatophobia is a fear of the eyes.",
  "80 percent of all learning comes through the eyes.",
  "Your eyes can detect a candle flame 1.7 miles away.",
  "Your iris has 256 unique characteristics; your fingerprint has just 40.",
  "Heterochromia is the medical term for having two different colored eyes.",
  "Only 1/6 of your eyeball is visible.",
  "The average person blinks 12 times a minute ",
  "The shark cornea is nearly identical to the human cornea, and has even been used in human eye surgery!",
  "The optic nerve contains more than one million nerve cells.",
  "Your eye is the fastest contracting muscle in the body, contracting in less than 1/100th of a second.",
  "Eyelashes have an average lifespan of five months.",
  "The space between your eyebrows is called the Glabella.",
  "About half of the human brain is dedicated to vision and seeing.",
  "Dogs can’t distinguish between red and green.",
  "The human eye can see 500 shades of grey.",
  "80% of vision impairment worldwide is curable.",
  "Everyone has one eye that is slightly stronger than the other.",
  "Oily fish, vitamin A and vitamin C can all help to preserve good eyesight",
  "You see things upside down - it is your brain which turns the image the right way up",
  "A blink typically lasts 100-150 milliseconds.",
  "If the human eye was a digital camera, it would have 576 megapixels.",
  "The world’s most common eye colour is brown.",
];
